version: '3'
services:
  api:
    container_name: api-container
    build: ./backend-node
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000
    ports:
      - "5000:5000"
  client:
    container_name: client-container
    build: ./frontend
    environment:
      MONGO_ATLAS_PW: smritigoel
      JWT_KEY: pluto
    ports:
      - "3000:3000"